name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y git make clang llvm libelf-dev pkg-config gcc g++-multilib

      - name: Checkout
        uses: actions/checkout@v2

      - name: make
        run: C_INCLUDE_PATH=/usr/include/x86_64-linux-gnu/ make
